inherit_from:
  - .rubocop_rspec.yml
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'db/**/*'
    - 'spec/dummy/**/*'
    - 'bin/{rails,rake}'
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Naming/MethodParameterName:
  MinNameLength: 1

Style/FormatStringToken:
  Exclude:
    - config/routes.rb